name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure provider '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AI Vault Version
      description: Run `ai-vault --version`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: "v20.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider
      description: Which AI provider were you using?
      options:
        - Grok
        - ChatGPT
        - Claude
        - Gemini
        - Other
        - Not provider-specific

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (run with --debug flag)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
