name: New Provider Request
description: Request support for a new AI platform
title: "[Provider]: "
labels: ["enhancement", "provider"]
body:
  - type: markdown
    attributes:
      value: |
        Request support for a new AI platform!

  - type: input
    id: provider-name
    attributes:
      label: Provider Name
      description: Name of the AI platform
      placeholder: "e.g., Perplexity, Anthropic, etc."
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Provider Website
      description: Official website URL
      placeholder: "https://..."
    validations:
      required: true

  - type: dropdown
    id: api-availability
    attributes:
      label: API Availability
      description: Does the provider have a public API?
      options:
        - "Yes - Public API available"
        - "No - Would need web scraping"
        - "Unknown"
    validations:
      required: true

  - type: input
    id: api-docs
    attributes:
      label: API Documentation URL
      description: Link to API documentation (if available)
      placeholder: "https://..."

  - type: checkboxes
    id: features
    attributes:
      label: Features to Support
      description: What features should be archived?
      options:
        - label: Chat conversations
        - label: Images generated by AI
        - label: Videos generated by AI
        - label: Code artifacts
        - label: File attachments
        - label: Citations/sources

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you want to archive this provider?
      placeholder: I use this platform for...
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can provide test account access
        - label: I'm willing to help implement this provider

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
